version: '3.4'

services:

  app-without-reload:
    image: fastapi-issue-548
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "fastapi-issue-548 --version && python -m app"
    volumes:
      - ./app:/home/appuser/app/app:ro
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
